2017:
 Registration: 200.00
 Tuition: 400.00
 Dorm: 240.00
 Single Room: 100
 Sunday Arrival: 100
 Meals: 260.00
 No Breakfast: -60
 Commemorative Wine Glass: 20.0
 Tshirts: 20.00
 Donation: 0.00
 Deposit: 150.00
 Credit Card Flat Rate: .30
 Credit Card Percentage: 3.0
 Board Member Flat Rate: 150.00

2016:
 Registration: 200.00
 Tuition: 400.00
 Dorm: 240.00
 Single Room: 100
 Sunday Arrival: 100
 Meals: 260.00
 No Breakfast: -60
 Commemorative Wine Glass: 0
 Tshirts: 20.00
 Donation: 0.00
 Deposit: 150.00
 Credit Card Flat Rate: .30
 Credit Card Percentage: 3.0
 Board Member Flat Rate: 150.00

2015:
 Registration: 190.00
 Tuition: 375.00
 Dorm: 200.00
 Single Room: 100
 Sunday Arrival: 100
 Meals: 235.00
 No Breakfast: -55
 Commemorative Wine Glass: 25
 Tshirts: 20.00
 Donation: 0.00
 Deposit: 150.00
 Credit Card Flat Rate: .30
 Credit Card Percentage: 3.0
 Board Member Flat Rate: 150.00

2014:
 Registration: 190.00
 Tuition: 375.00
 Dorm: 185.00
 Single Room: 100
 Sunday Arrival: 100
 Meals: 225.00
 No Breakfast: -55
 Tshirts: 20.00
 Donation: 0.00
 Deposit: 150.00
 Credit Card Flat Rate: .30
 Credit Card Percentage: 3.0

2013:
 Registration: 190.00
 Tuition: 375.00
 Dorm: 185.00
 Meals: 225.00
 Tshirts: 20.00
 Sunday Arrival: 100
 Commemorative Wine Glass: 20
 Single Room: 65
 Discount: -10.00
 Board Member Flat Rate: 250.00
 Deposit: 150.00
 Credit Card Flat Rate: .30
 Credit Card Percentage: 3.0

2012:
 Registration: 190.00
 Tuition: 375.00
 Dorm: 185.00
 Meals: 225.00
 Tshirts: 20.00
 Sunday Arrival: 100
 Commemorative Wine Glass: 20
 Single Room: 65
 Discount: -10.00
 Board Member Flat Rate: 250.00
 Deposit: 150.00
 Credit Card Flat Rate: .30
 Credit Card Percentage: 3.0

2011:
 Registration: 125.00
 Tuition: 350.00
 Dorm: 175.00
 Meals: 200.00
 Tshirts: 20.00
 Discount: -10.00
# Changed 5/2010 per Tricia		
## Board Member Flat Rate: 385.00
 Board Member Flat Rate: 0.00
 Deposit: 125.00
 Credit Card Flat Rate: .30
 Credit Card Percentage: 3.0

#2010:
 Registration: 125.00
 Tuition: 350.00
 Dorm: 175.00
 Meals: 200.00
 Tshirts: 20.00
 Discount: -10.00
# Changed 5/2010 per Tricia		
# Board Member Flat Rate: 385.00
 Board Member Flat Rate: 0.00
 Deposit: 125.00
 Credit Card Flat Rate: .30
 Credit Card Percentage: 3.0

#  TESTING
#2011:
# Registration: 1.00
# Tuition: 1.00
# Dorm: 0.50
# Meals: 0.50
# Tshirts: 20.00
# Discount: -10.00
# Board Member Flat Rate: 2.00
# Deposit: 1.00
# Credit Card Flat Rate: .30
# Credit Card Percentage: 3.0

